In [1]:
import sys
if not any(['tskit-ld-proto' in s for s in sys.path]):
    sys.path.append('/home/lkirk/repo/tskit-ld-proto')

In [2]:
import numpy as np

from tskit_ld_proto.ld_proto import _two_site_general_stat

In [3]:
correlated = (
    np.array(
        [[0, 1, 1, 0, 2, 2, 1, 0, 1],
         [1, 2, 2, 1, 0, 0, 2, 1, 2]]
    ),
    np.array([3, 3])
)

In [4]:
correlated_biallelic = (
    np.array(
        [[0, 0, 0, 0, 1, 1, 1, 1],
         [0, 0, 0, 0, 1, 1, 1, 1]]
    ),
    np.array([2, 2])
)

In [5]:
uncorrelated = (
    np.array(
        [[0, 0, 0, 1, 1, 1, 2, 2, 2],
         [0, 1, 2, 0, 1, 2, 0, 1, 2]]
    ),
    np.array([3, 3])
)

In [6]:
uncorrelated_biallelic = (
    np.array(
        [[0, 0, 0, 0, 1, 1, 1, 1],
         [1, 1, 0, 0, 0, 0, 1, 1]]
    ),
    np.array([2, 2])
)

In [7]:
repulsion_biallelic = (
    np.array(
        [[0, 0, 0, 0, 1, 1, 1, 1],
         [1, 1, 1, 1, 0, 0, 0, 0]]
    ),
    np.array([2, 2])
)

In [18]:
for r in repulsion_biallelic[0]:
    print(' & '.join(map(str, r)) + ' \\\\')

0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 \\
1 & 1 & 1 & 1 & 0 & 0 & 0 & 0 \\


In [8]:
def D(w_AB, w_Ab, w_aB, n):
    p_AB = w_AB / float(n)
    p_Ab = w_Ab / float(n)
    p_aB = w_aB / float(n)

    p_A = p_AB + p_Ab
    p_B = p_AB + p_aB

    return p_AB - (p_A * p_B)

In [9]:
_two_site_general_stat(*correlated, D, 'total')

array([[0., 0.],
       [0., 0.]])

In [10]:
_two_site_general_stat(*uncorrelated, D, 'total')

array([[0., 0.],
       [0., 0.]])

In [11]:
_two_site_general_stat(*correlated_biallelic, D, 'total')

array([[0., 0.],
       [0., 0.]])

In [12]:
_two_site_general_stat(*uncorrelated_biallelic, D, 'total')

array([[0., 0.],
       [0., 0.]])

In [13]:
_two_site_general_stat(*repulsion_biallelic, D, 'total')

array([[0., 0.],
       [0., 0.]])

In [14]:
_two_site_general_stat(*correlated, D, 'total', polarized=True)

array([[ 0.05555556, -0.01851852],
       [-0.01851852,  0.04320988]])

In [15]:
_two_site_general_stat(*uncorrelated, D, 'total', polarized=True)

array([[0.05555556, 0.        ],
       [0.        , 0.05555556]])

In [16]:
_two_site_general_stat(*correlated_biallelic, D, 'total', polarized=True)

array([[0.25, 0.25],
       [0.25, 0.25]])

In [17]:
_two_site_general_stat(*uncorrelated_biallelic, D, 'total', polarized=True)

array([[0.25, 0.  ],
       [0.  , 0.25]])

In [18]:
_two_site_general_stat(*repulsion_biallelic, D, 'total', polarized=True)

array([[ 0.25, -0.25],
       [-0.25,  0.25]])

In [19]:
def r2(w_AB, w_Ab, w_aB, n):
    p_AB = w_AB / float(n)
    p_Ab = w_Ab / float(n)
    p_aB = w_aB / float(n)

    p_A = p_AB + p_Ab
    p_B = p_AB + p_aB

    D = p_AB - (p_A * p_B)
    denom = p_A * p_B * (1 - p_A) * (1 - p_B)

    if denom == 0 and D == 0:
        return np.nan

    return (D * D) / denom

In [20]:
_two_site_general_stat(*correlated, r2, 'hap_weighted')

array([[1., 1.],
       [1., 1.]])

In [21]:
_two_site_general_stat(*uncorrelated, r2, 'hap_weighted')

array([[1., 0.],
       [0., 1.]])

In [22]:
_two_site_general_stat(*correlated_biallelic, r2, 'hap_weighted')

array([[1., 1.],
       [1., 1.]])

In [23]:
_two_site_general_stat(*uncorrelated_biallelic, r2, 'hap_weighted')

array([[1., 0.],
       [0., 1.]])

In [24]:
_two_site_general_stat(*repulsion_biallelic, r2, 'hap_weighted')

array([[1., 1.],
       [1., 1.]])

In [25]:
_two_site_general_stat(*correlated, r2, 'hap_weighted', polarized=True)

array([[0.66666667, 0.44444444],
       [0.44444444, 0.77777778]])

In [26]:
_two_site_general_stat(*uncorrelated, r2, 'hap_weighted', polarized=True)

array([[0.66666667, 0.        ],
       [0.        , 0.66666667]])

In [27]:
_two_site_general_stat(*correlated_biallelic, r2, 'hap_weighted', polarized=True)

array([[0.5, 0.5],
       [0.5, 0.5]])

In [28]:
_two_site_general_stat(*uncorrelated_biallelic, r2, 'hap_weighted', polarized=True)

array([[0.5, 0. ],
       [0. , 0.5]])

In [29]:
_two_site_general_stat(*repulsion_biallelic, r2, 'hap_weighted', polarized=True)

array([[0.5, 0. ],
       [0. , 0.5]])

In [30]:
_two_site_general_stat(
    np.array([[0, 0, 1, 2],[1, 2, 0 ,0 ]]), np.array([3, 3]), r2, 'hap_weighted', polarized=True)

array([[0.5, 0. ],
       [0. , 0.5]])

In [31]:
_two_site_general_stat(
    np.array([[0, 0, 1, 2],[1, 2, 0 ,0 ]]), np.array([3, 3]), r2, 'hap_weighted')

array([[1.        , 0.33333333],
       [0.33333333, 1.        ]])

In [32]:
_two_site_general_stat(
    np.array([[0, 1, 2],[1, 0, 0]]), np.array([3, 2]), r2, 'hap_weighted', polarized=True)

array([[0.66666667, 0.        ],
       [0.        , 0.33333333]])

In [33]:
_two_site_general_stat(
    np.array([[0, 1, 2],[1, 0, 0]]), np.array([3, 2]), r2, 'hap_weighted')

array([[1. , 0.5],
       [0.5, 1. ]])

In [34]:
def D_prime(w_AB, w_Ab, w_aB, n):
    p_AB = w_AB / float(n)
    p_Ab = w_Ab / float(n)
    p_aB = w_aB / float(n)

    p_A = p_AB + p_Ab
    p_B = p_AB + p_aB

    D = p_AB - (p_A * p_B)
    if D >= 0:
        return D / min(p_A * (1 - p_B), (1 - p_A) * p_B)
    return D / min(p_A * p_B, (1 - p_A) * (1 - p_B))

In [35]:
_two_site_general_stat(*correlated, D_prime, 'total')

array([[-0.33333333, -0.33333333],
       [-0.33333333, -0.33333333]])

In [36]:
_two_site_general_stat(*correlated, D_prime, 'hap_weighted')

array([[1., 1.],
       [1., 1.]])

In [37]:
_two_site_general_stat(*uncorrelated, D_prime, 'total')

array([[-0.33333333,  0.        ],
       [ 0.        , -0.33333333]])

In [38]:
_two_site_general_stat(*uncorrelated, D_prime, 'hap_weighted')

array([[1., 0.],
       [0., 1.]])

In [39]:
_two_site_general_stat(*correlated_biallelic, D_prime, 'total')

array([[0., 0.],
       [0., 0.]])

In [40]:
_two_site_general_stat(*uncorrelated_biallelic, D_prime, 'total')

array([[0., 0.],
       [0., 0.]])

In [41]:
_two_site_general_stat(*repulsion_biallelic, D_prime, 'total')

array([[0., 0.],
       [0., 0.]])

In [42]:
_two_site_general_stat(*correlated, D_prime, 'total', polarized=True)

array([[ 0. , -0.5],
       [-0.5,  0. ]])

In [43]:
_two_site_general_stat(*uncorrelated, D_prime, 'total', polarized=True)

array([[-2.77555756e-17,  0.00000000e+00],
       [ 0.00000000e+00, -2.77555756e-17]])

In [44]:
_two_site_general_stat(*correlated_biallelic, D_prime, 'total', polarized=True)

array([[1., 1.],
       [1., 1.]])

In [45]:
_two_site_general_stat(*uncorrelated_biallelic, D_prime, 'total', polarized=True)

array([[1., 0.],
       [0., 1.]])

In [46]:
_two_site_general_stat(*repulsion_biallelic, D_prime, 'total', polarized=True)

array([[ 1., -1.],
       [-1.,  1.]])

In [47]:
def r(w_AB, w_Ab, w_aB, n):
    p_AB = w_AB / float(n)
    p_Ab = w_Ab / float(n)
    p_aB = w_aB / float(n)

    p_A = p_AB + p_Ab
    p_B = p_AB + p_aB

    D = p_AB - (p_A * p_B)
    denom = p_A * p_B * (1 - p_A) * (1 - p_B)

    if denom == 0 and D == 0:
        return np.nan

    return D / np.sqrt(denom)

In [48]:
_two_site_general_stat(*correlated, r, 'hap_weighted')

array([[1., 1.],
       [1., 1.]])

In [49]:
_two_site_general_stat(*uncorrelated, r, 'hap_weighted')

array([[1., 0.],
       [0., 1.]])

In [50]:
_two_site_general_stat(*correlated_biallelic, r, 'hap_weighted')

array([[1., 1.],
       [1., 1.]])

In [51]:
_two_site_general_stat(*uncorrelated_biallelic, r, 'hap_weighted')

array([[1., 0.],
       [0., 1.]])

In [52]:
_two_site_general_stat(*repulsion_biallelic, r, 'hap_weighted')

array([[1., 1.],
       [1., 1.]])

In [53]:
_two_site_general_stat(*correlated, r, 'hap_weighted', polarized=True)

array([[0.66666667, 0.44444444],
       [0.44444444, 0.77777778]])

In [54]:
_two_site_general_stat(*uncorrelated, r, 'hap_weighted', polarized=True)

array([[0.66666667, 0.        ],
       [0.        , 0.66666667]])

In [55]:
_two_site_general_stat(*correlated_biallelic, r, 'hap_weighted', polarized=True)

array([[0.5, 0.5],
       [0.5, 0.5]])

In [56]:
_two_site_general_stat(*uncorrelated_biallelic, r, 'hap_weighted', polarized=True)

array([[0.5, 0. ],
       [0. , 0.5]])

In [57]:
_two_site_general_stat(*repulsion_biallelic, r, 'hap_weighted', polarized=True)

array([[0.5, 0. ],
       [0. , 0.5]])

In [58]:
def Dz(w_AB, w_Ab, w_aB, n):
    p_AB = w_AB / float(n)
    p_Ab = w_Ab / float(n)
    p_aB = w_aB / float(n)

    p_A = p_AB + p_Ab
    p_B = p_AB + p_aB

    D = p_AB - (p_A * p_B)

    return D * (1 - 2 * p_A) * (1 - 2 * p_B)

In [59]:
def pi2(w_AB, w_Ab, w_aB, n):
    p_AB = w_AB / float(n)
    p_Ab = w_Ab / float(n)
    p_aB = w_aB / float(n)

    p_A = p_AB + p_Ab
    p_B = p_AB + p_aB

    return p_A * (1 - p_A) * p_B * (1 - p_B)

In [60]:
Dz(3, 0, 0, 4)

0.046875

In [61]:
Dz(0, 1, 3, 4)

0.046875

In [62]:
_two_site_general_stat(
    np.array([[0, 0, 1, 2],[1, 2, 0 ,0 ]]), np.array([3, 3]), r2, 'hap_weighted', polarized=True, debug=True)

a: [0 0 1 2] b: [0 0 1 2]
[[2 0 0]
 [0 1 0]
 [0 0 1]]
wAB	wAb	waB	stat	hap_prop
1	0	0	1.0	0.25
0	1	1	0.1111111111111111	0.0
0	1	1	0.1111111111111111	0.0
1	0	0	1.0	0.25
--------------------------------------------------------
a: [0 0 1 2] b: [1 2 0 0]
[[0 1 1]
 [1 0 0]
 [1 0 0]]
wAB	wAb	waB	stat	hap_prop
0	1	1	0.1111111111111111	0.0
0	1	1	0.1111111111111111	0.0
0	1	1	0.1111111111111111	0.0
0	1	1	0.1111111111111111	0.0
--------------------------------------------------------
a: [1 2 0 0] b: [1 2 0 0]
[[2 0 0]
 [0 1 0]
 [0 0 1]]
wAB	wAb	waB	stat	hap_prop
1	0	0	1.0	0.25
0	1	1	0.1111111111111111	0.0
0	1	1	0.1111111111111111	0.0
1	0	0	1.0	0.25
--------------------------------------------------------


array([[0.5, 0. ],
       [0. , 0.5]])

In [63]:
_two_site_general_stat(
    np.array([[0, 0, 1, 2],[1, 2, 0 ,0 ]]), np.array([3, 3]), r2, 'hap_weighted')

array([[1.        , 0.33333333],
       [0.33333333, 1.        ]])

In [64]:
_two_site_general_stat(
    np.array([[0, 0, 1, 2],[1, 2, 0 ,0 ]]), np.array([3, 3]), D_prime, 'hap_weighted', polarized=True)

array([[0.5, 0. ],
       [0. , 0.5]])

In [65]:
_two_site_general_stat(
    np.array([[0, 0, 1, 2],[1, 2, 0 ,0 ]]), np.array([3, 3]), D_prime, 'hap_weighted')

array([[1., 1.],
       [1., 1.]])