# Validation of python prototype code

This notebook provides a basic demonstration of the intended behavior of our summary functions.

## Add prototype python code to the path

In [1]:
import os
import sys
if not any(['tskit-ld-proto' in s for s in sys.path]):
    sys.path.append(os.path.abspath('.'))

In [2]:
import numpy as np

from tskit_ld_proto.ld_proto import _two_site_general_stat
from tskit_ld_proto.summary_functions import r, r2, D, D_prime, Dz, pi2

## Results display functionality

In [3]:
from IPython.display import display_latex, display_markdown

In [4]:
DISPLAY_MODE = 'latex'
def display_matrix(m, mode=DISPLAY_MODE, round_decimals=5):
    m = m.copy()
    if round_decimals:
        m = np.round(m, decimals=round_decimals)
    if mode == 'latex':
        display_latex(matrix_to_latex(m), raw=True)
    elif mode == 'raw_latex':
        print(matrix_to_latex(m))
    elif mode == 'print':
        print(m)
    else:
        raise ValueError(mode)


def matrix_to_latex(a):
    assert len(a.shape) == 2, 'this fn works on matricies only'
    out = r'$\left(\begin{array}'
    out += f'{{{"c" * a.shape[1]}}}'
    for r in a:
        out += ' & '.join(map(str, r)) + ' \\\\'
    out += r'\end{array}\right)$'
    return out

## Test Cases

In [5]:
CORRELATED = (
    np.array(
        [[0, 1, 1, 0, 2, 2, 1, 0, 1],
         [1, 2, 2, 1, 0, 0, 2, 1, 2]]
    ),
    np.array([3, 3])
)

In [6]:
CORRELATED_BIALLELIC = (
    np.array(
        [[0, 0, 0, 0, 1, 1, 1, 1],
         [0, 0, 0, 0, 1, 1, 1, 1]]
    ),
    np.array([2, 2])
)

In [7]:
UNCORRELATED = (
    np.array(
        [[0, 0, 0, 1, 1, 1, 2, 2, 2],
         [0, 1, 2, 0, 1, 2, 0, 1, 2]]
    ),
    np.array([3, 3])
)

In [8]:
UNCORRELATED_BIALLELIC = (
    np.array(
        [[0, 0, 0, 0, 1, 1, 1, 1],
         [1, 1, 0, 0, 0, 0, 1, 1]]
    ),
    np.array([2, 2])
)

In [9]:
REPULSION_BIALLELIC = (
    np.array(
        [[0, 0, 0, 0, 1, 1, 1, 1],
         [1, 1, 1, 1, 0, 0, 0, 0]]
    ),
    np.array([2, 2])
)

In [10]:
TEST_CASES = {k: v for k, v in locals().items() if 'CORRELATED' in k or 'ALLELIC' in k}

## Test Results

In [11]:
display_latex(r'$D$ unpolarized', raw=True)
for case_name, data in TEST_CASES.items():
    print(case_name.lower())
    display_matrix(_two_site_general_stat(*data, D, 'total'))

correlated


correlated_biallelic


uncorrelated


uncorrelated_biallelic


repulsion_biallelic


In [12]:
display_latex(r'$D$ polarized', raw=True)
for case_name, data in TEST_CASES.items():
    print(case_name.lower())
    display_matrix(_two_site_general_stat(*data, D, 'total', polarized=True))

correlated


correlated_biallelic


uncorrelated


uncorrelated_biallelic


repulsion_biallelic


In [13]:
display_latex(r'$r^{2}$ unpolarized', raw=True)
for case_name, data in TEST_CASES.items():
    print(case_name.lower())
    display_matrix(_two_site_general_stat(*data, r2, 'hap_weighted'))

correlated


correlated_biallelic


uncorrelated


uncorrelated_biallelic


repulsion_biallelic


In [14]:
display_latex(r'$r^{2}$ polarized', raw=True)
for case_name, data in TEST_CASES.items():
    print(case_name.lower())
    display_matrix(_two_site_general_stat(*data, r2, 'hap_weighted', polarized=True))

correlated


correlated_biallelic


uncorrelated


uncorrelated_biallelic


repulsion_biallelic


In [15]:
display_latex(r'$D^{\prime}$ polarized', raw=True)
for case_name, data in TEST_CASES.items():
    print(case_name.lower())
    display_matrix(_two_site_general_stat(*data, D_prime, 'total', polarized=True))

correlated


correlated_biallelic


uncorrelated


uncorrelated_biallelic


repulsion_biallelic


In [16]:
display_latex(r'$r$ unpolarized', raw=True)
for case_name, data in TEST_CASES.items():
    print(case_name.lower())
    display_matrix(_two_site_general_stat(*data, r, 'hap_weighted'))

correlated


correlated_biallelic


uncorrelated


uncorrelated_biallelic


repulsion_biallelic


In [17]:
display_latex(r'$r$ polarized', raw=True)
for case_name, data in TEST_CASES.items():
    print(case_name.lower())
    display_matrix(_two_site_general_stat(*data, r, 'hap_weighted', polarized=True))

correlated


correlated_biallelic


uncorrelated


uncorrelated_biallelic


repulsion_biallelic


## Investigations/musings

In [18]:
_two_site_general_stat(
    np.array([[0, 0, 1, 2],[1, 2, 0 ,0 ]]), np.array([3, 3]), r2, 'hap_weighted', polarized=True)

array([[0.5, 0. ],
       [0. , 0.5]])

In [19]:
_two_site_general_stat(
    np.array([[0, 0, 1, 2],[1, 2, 0 ,0 ]]), np.array([3, 3]), r2, 'hap_weighted')

array([[1.        , 0.33333333],
       [0.33333333, 1.        ]])

In [20]:
_two_site_general_stat(
    np.array([[0, 1, 2],[1, 0, 0]]), np.array([3, 2]), r2, 'hap_weighted', polarized=True)

array([[0.66666667, 0.        ],
       [0.        , 0.33333333]])

In [21]:
_two_site_general_stat(
    np.array([[0, 1, 2],[1, 0, 0]]), np.array([3, 2]), r2, 'hap_weighted')

array([[1. , 0.5],
       [0.5, 1. ]])

In [22]:
_two_site_general_stat(*CORRELATED, D_prime, 'total')

array([[-0.33333333, -0.33333333],
       [-0.33333333, -0.33333333]])

In [23]:
_two_site_general_stat(*CORRELATED, D_prime, 'hap_weighted')

array([[1., 1.],
       [1., 1.]])

In [24]:
_two_site_general_stat(*UNCORRELATED, D_prime, 'total')

array([[-0.33333333,  0.        ],
       [ 0.        , -0.33333333]])

In [25]:
_two_site_general_stat(*UNCORRELATED, D_prime, 'hap_weighted')

array([[1., 0.],
       [0., 1.]])

In [26]:
_two_site_general_stat(*CORRELATED_BIALLELIC, D_prime, 'total')

array([[0., 0.],
       [0., 0.]])

In [27]:
_two_site_general_stat(*UNCORRELATED_BIALLELIC, D_prime, 'total')

array([[0., 0.],
       [0., 0.]])

In [28]:
_two_site_general_stat(*REPULSION_BIALLELIC, D_prime, 'total')

array([[0., 0.],
       [0., 0.]])